apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}-cfg
  labels:
    {{- if .Values.subChartName }}
    subChart: {{ .Values.subChartName }}
    {{- end }}
data:
  application.yaml: |-
    {{- with .Values.APPLICATION_YAML }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
