apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
  labels:
    app: {{ .Values.nameOverride | default .Chart.Name }}
    {{- if .Values.subChartName }}
    subChart: {{ .Values.subChartName }}
    {{- end }}
spec:
  {{ if ge (int .Values.nodePort) 0 }}
  type: NodePort
  {{ end }}
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      {{- if gt (int .Values.nodePort) 0 }}
      nodePort: {{ .Values.nodePort }}
      {{- else}}
      nodePort: null
      {{- end }}
  selector:
    app: {{ .Values.nameOverride | default .Chart.Name }}
